# Ansible needs an "inventory" to know which machines to configure.
# For local setup, we tell it to run on localhost without SSH.
[local]
localhost ansible_connection=local ansible_python_interpreter=auto
